### ISSUE TITLE
抽屉可以使用新的NavigationView控件

### ISSUE THREAD

**Issue by callmepeanut** [Garnel/WanquRibao#1]
我将抽屉使用NavigationView控件替换掉了，更符合MD规范，代码量也减少了。修改后代码如下：
https://github.com/callmepeanut/WanquRibao/tree/new_navigation_drawer
要是没问题的话，我就提一个pull request

**Comment by maogm12** [comment]
@callmepeanut  谢谢~
你测试没有问题就提吧，我merge了去发个新版本
